USE DemoDb
GO

CREATE TABLE WorldBorders
(
	FIPS NVARCHAR(255) NULL,
	ISO2 NVARCHAR(255) NULL,
	ISO3 NVARCHAR(255) NULL,
	UN INT NULL,
	NAME NVARCHAR(255) NULL,
	POP2005 BIGINT NULL,
	REGION INT NULL,
	SUBREGION INT NULL,
	LON FLOAT NULL,
	LAT FLOAT NULL,
	GEOM geometry NULL,
	geog geography NULL, 
)